---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::526404758660:role/SS-EKS-Nodes-test-NodeInstanceRole-XW6GC49WPIGG
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::526404758660:role/ss-role-BG
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:masters
