## Sample application deployment YAML file
## kubectl apply -f manifest.yml

---
apiVersion: v1
kind: Service
metadata:
  name: tracks
  labels:
    app: tracks
    group: motocross
spec:
  selector: 
    app: tracks
  ports:
  - port: 4567
  
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tracks
  labels:
    app: tracks
    group: motocross
spec:
  replicas: 3
  template:
    metadata: 
      labels:
        app: tracks
    spec:
      containers:
      - name: tracks
        image: christopherhein/mx-tracks:latest
        ports:
        - containerPort: 4567
        
---
apiVersion: v1
kind: Service
metadata:
  name: laptimes
  labels:
    app: laptimes
    group: motocross
spec:
  selector: 
    app: laptimes
  ports:
  - port: 5000
  
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: laptimes
  labels:
    app: laptimes
    group: motocross
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: laptimes
    spec:
      containers:
      - name: laptimes
        image: christopherhein/mx-laptimes:latest
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    group: motocross
spec:
  selector: 
    app: webapp
  ports:
  - port: 80
    targetPort: http-server
    name: http
  - port: 443
    targetPort: http-server
    name: ssl
  type: LoadBalancer
  
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
    group: motocross
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: christopherhein/mx-webapp:latest
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: TRACKS_HOST
          value: tracks
        - name: TRACKS_PORT
          value: "4567"
        - name: LAPTIMES_HOST
          value: laptimes
        - name: LAPTIMES_PORT
          value: "5000"
